# Generated by Django 6.0 on 2026-01-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_player_count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
