# Generated by Django 6.0 on 2026-01-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamerecord',
            name='secret',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
